# Generated by Django 5.2.7 on 2025-11-01 21:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cobertura_agua', models.FloatField(help_text='Porcentaje de cobertura de agua potable', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('ARTICULO', 'Artículo'), ('VIDEO', 'Video'), ('INFOGRAFIA', 'Infografía'), ('DOCUMENTO', 'Documento')], max_length=20)),
                ('archivo', models.FileField(upload_to='recursos_educativos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('CORTE', 'Corte de Agua'), ('FUGA', 'Fuga de Agua'), ('CALIDAD', 'Problema de Calidad'), ('OTROS', 'Otros Problemas')], max_length=20)),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='REPORTADO', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion_lat', models.FloatField()),
                ('ubicacion_lng', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqualand_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaAPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion_lat', models.FloatField()),
                ('ubicacion_lng', models.FloatField()),
                ('poblacion_atendida', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqualand_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cobertura_urbana', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cobertura_rural', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('usuarios_afectados', models.IntegerField(default=0)),
                ('incidencias_mes', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqualand_app.region')),
            ],
            options={
                'unique_together': {('region', 'fecha')},
            },
        ),
    ]
