# Generated by Django 5.2.7 on 2025-11-05 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqualand_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='cobertura_agua',
            field=models.FloatField(help_text='Porcentaje de cobertura de agua potable', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=9999999999),
        ),
    ]
