# Generated by Django 5.2.7 on 2025-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqualand_app', '0002_alter_region_cobertura_agua_alter_region_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='direccion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
