# Generated by Django 4.2.17 on 2025-12-05 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqualand_app', '0005_update_superuser_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='cobertura_agua',
            field=models.FloatField(help_text='Porcentaje de cobertura de agua potable', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
